
# Snippets

## Check if a file exists

```

! DEFINE FEXISTS as LOGICAL
LOGICAL FEXISTS 
INQUIRE (FILE = 'Filename.DAT', EXIST = FEXISTS)
IF( FEXISTS )THEN

ELSE

ENDIF
```

## Open and close files

To open files in FORTRAN simply use:
  
  `OPEN(7, FILE = 'hello.txt', STATUS = 'UNKNOWN')`
where 7 = the unique number assigned to the file that is being opened.

To close the files we can simply use :
  
  `CLOSE(7)`

If we want to delete the file then we can use 

`CLOSE(7, STATUS = 'DELETE')`

A simple example is given here:
  
  ```
open (unit=CHROMOSOME_UNIT, file=filename, status='old', &
        iostat=open_status, action='read', position='rewind')
if ( open_status /= 0 ) then
print *, 'Could not open ',filename,' for reading.', &
  'unit = ', unit
stop
endif
```
The open statement uses a number of tags to specify which file to open and how it will be used.

**Required tags:**
  
  * unit: integer unit number to be used by read, write, and close.
* filename: String constant, variable, or expression representing the absolute or relative pathname of the file.
* status: String constant, variable, or expression that reduces to:
  * 'old': For existing files, usually used when reading.
* 'new': Used when writing to a file that does not yet exist.
* 'replace': Used to overwrite a file that already exists.
* iostat: Integer variable to receive the status of the open operation. If the file is opened successfully, the variable is set to 0. Otherwise, it will contain a non-zero error code that indicates why the file could not be opened. (Does not exist, no permission, etc.)

**Optional tags:**
  
  * action: String
* 'read': Open for reading only
* 'write': Open for writing only
* 'readwrite': Allow both reading and writing
* position: String
* 'rewind': Start at beginning of file
* 'append': Writes add to file rather than overwrite


## Append files in FORTRAN

To do the appends in FORTRAN we could do something like:
  ```
OPEN(95,FILE=OUTDIR//'*.OUT',POSITION='APPEND',STATUS='OLD',  FORM='BINARY')
! Some code 
CLOSE(95) 
```

In the above code 95 is just used arbitrarily.

## Allocatable arrays in FORTRAN 90

In FORTRAN 90, one can assign allocatable arrays with the syntax as follows:
  
```
REAL,ALLOCATABLE,DIMENSION(:)::RSSBCW
REAL, ALLOCATABLE, DIMENSION(:,:):: TESTDF
```

In the above example, RSSBCW is a 1-D vector whereas TESTDF is a 2 dimensional array.


